Torrentinator/Models/ActiveTorrentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Torrentinator.Models
{
    public class ActiveTorrentViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string JSId
        {
            get
            {
                return Regex.Replace(this.Id.ToLower(), @"([^\w])+", "_");
            }
        }
    }
}

Torrentinator/Models/ErrorViewModel.cs
using System;

namespace Torrentinator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string ErrorMessage { get; set; }
        public string ErrorStack { get; set; }
    }
}

Torrentinator/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Torrentinator.Models
{
    public class HomeViewModel
    {
        public bool Connected { get; set; }
        public string ConnectionError { get; set; }
        public string Address { get; set; }

        public int SocksPort { get; set; }

        public int ControlPort { get; set; }

        public string TorIP { get; set; }

        public string CurrentTorIP { get; set; }
    }
}

Torrentinator/Models/TorConnectResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Torrentinator.Models
{
    public class TorConnectResult
    {
        public bool Success { get; }
        public string TorIP { get; }
        public string ErrorMessage { get; }

        internal TorConnectResult(string torIP, Exception ex)
        {
            this.TorIP = torIP;
            if (ex == null)
                this.Success = true;
            else
            {
                this.Success = false;
                this.ErrorMessage = ex.ToString();
            }
        }
    }
}

Torrentinator/Models/TorrentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Torrentinator.Library.Models;
using Torrentinator.Types;

namespace Torrentinator.Models
{
    public class TorrentViewModel : Torrent
    {
        [UIHint("BytesFormat")]
        public long Bytes => this.Length;
        public Progress DownloadProgress { get;  } = new Progress();

        internal static TorrentViewModel Create(Torrent torrent)
        {
            var tvm = new TorrentViewModel()
            {
                TorrentId = torrent.TorrentId,
                Title = torrent.Title,
                Description = torrent.Description,
                Length = torrent.Length,
                Published = torrent.Published,
                Url = torrent.Url,
                Status = torrent.Status,
                Downloaded = torrent.Downloaded
            };
            tvm.DownloadProgress.TorrentId = tvm.TorrentId;
            tvm.DownloadProgress.Completed = tvm.Downloaded;
            tvm.DownloadProgress.Total = tvm.Length;

            return tvm;
        }
    }
}

Torrentinator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Torrentinator.Business;
using Torrentinator.Library.Services;
using Torrentinator.Models;

namespace Torrentinator.Controllers
{
    public class HomeController : Controller
    {
        private ITorrentService TorrentService;

        public HomeController(ITorrentService torrentService)
        {
            this.TorrentService = torrentService;
        }

        public IActionResult Index()
        {
            var model = new HomeViewModel()
            {
                Connected = this.TorrentService.Connected,
                ConnectionError = this.TorrentService.ConnectionError,
                Address = this.TorrentService.Address,
                ControlPort = this.TorrentService.ControlPort,
                SocksPort = this.TorrentService.SocksPort,
                TorIP = this.TorrentService.TorIP,
                CurrentTorIP = this.TorrentService.CurrentTorIP
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Reconnect()
        {
            this.TorrentService.Connect();
            return RedirectToAction("Index");
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Torrentinator/Controllers/TorrentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Torrentinator.Business;
using Torrentinator.Models;
using Torrentinator.Library.Services;
using Torrentinator.Library.Models;
using Torrentinator.Library.Repositories;

namespace Torrentinator.Controllers
{
    public class TorrentsController : Controller
    {
        private ITorrentRepository TorrentRepository;

        public TorrentsController(ITorrentRepository torrentRepository)
        {
            this.TorrentRepository = torrentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var torrents = (await this.TorrentRepository.GetTorrents()).Select(TorrentViewModel.Create);
            return View(torrents);
        }

        [HttpPost]
        public async Task<IActionResult> RefreshIndex()
        {
            await this.TorrentRepository.ImportTorrents();
            return Redirect("/Torrents");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteEverything()
        {
            await this.TorrentRepository.DeleteAllTorrents();
            return Redirect("/Torrents");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            await this.TorrentRepository.DeleteTorrent(id);
            return Redirect("/Torrents");
        }
        [HttpPost]
        [Route("/Torrents/Disable", Name = "withStatus")]
        public async Task<IActionResult> Disable(string id, TorrentStatus status)
        {
            await this.TorrentRepository.SetStatus(id, status);
            return Redirect("/Torrents");
        }
        [HttpPost]
        public async Task<IActionResult> Download(string id)
        {
            await this.TorrentRepository.StartDownload(id);
            return Redirect("/Torrents");
        }
    }
}

Torrentinator/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Torrentinator/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Torrentinator/Views/Home/Index.cshtml
@model Torrentinator.Models.HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-6">
        <h2>Tor Status</h2>
        <ul>
            <li>
                Status: <strong>@(Model.Connected ? "Connected" : "NOT CONNECTED")</strong>
                @if (!string.IsNullOrEmpty(Model.ConnectionError))
                {
                    <pre>@Model.ConnectionError</pre>
                
                    <form asp-action="Reconnect" asp-controller="Home">
                        <button type="submit">Reconnect</button>
                    </form>
                }
            </li>
            <li>Connect Address: <strong>@Model.Address:@Model.SocksPort</strong></li>
            <li>Control Address: <strong>@Model.Address:@Model.ControlPort</strong></li>
            <li>TOR IPs: <strong>@Model.TorIP @Model.CurrentTorIP</strong></li>
        </ul>
    </div>
</div>

Torrentinator/Views/Shared/DisplayTemplates/BytesFormat.cshtml
@using Torrentinator.Extensions;

@model long

<span>@Model.ToFriendlyBytes()</span>

Torrentinator/Views/Shared/DisplayTemplates/Progress.cshtml
@using Torrentinator.Extensions;
@model Torrentinator.Types.Progress

<div data-torrent="@Model.TorrentId">
    <div class="progress position-relative">
        <div class="progress-bar" role="progressbar" style="width: @Model.PercentComplete%" aria-valuenow="@Model.PercentComplete" aria-valuemin="0" aria-valuemax="100"></div>
        <small class="justify-content-center d-flex position-absolute w-100">@Model.PercentFormatted</small>
    </div>
    <div>
        <span>@Model.Completed.ToFriendlyBytes() of @Model.Total.ToFriendlyBytes()</span>
    </div>
</div>

Torrentinator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Torrentinator</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Torrentinator</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Torrents" asp-action="Index">Torrents</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Torrentinator</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" crossorigin="anonymous"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Torrentinator/Views/Torrents/Index.cshtml
@using Torrentinator.Library.Models
@model IEnumerable<Torrentinator.Models.TorrentViewModel>

@{
    ViewData["Title"] = "Torrents - Top 100 HD Movies";
}

<style type="text/css">
    tr.disabled-torrent {
        display: none;
    }
    td:nth-child(4) {
        text-align: right;
    }
</style>
<h2>Torrents</h2>

<div class="row" style="height:425px;">
    <div class="col-md-12">
        <canvas id="graph"></canvas>
    </div>
</div>
<form asp-controller="Torrents" method="post">
    <div class="btn-group" role="group" aria-label="Toolbar">
        <ul>
            <li><button asp-action="DeleteEverything" class="btn-primary">Delete All The Things</button></li>
            <li><button asp-action="RefreshIndex" class="btn-primary">Refresh Index</button></li>
        </ul>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Published)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="@(item.Status == TorrentStatus.Disabled ? "disabled-torrent" : "")">
                    <td>
                        <a href="#" onclick="return toggle('@item.TorrentId');">Description</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Published)
                    </td>
                    <td>
                        <button asp-action="Disable" type="submit" asp-route-id="@item.TorrentId" asp-route-status="@(item.Status == TorrentStatus.Ready ? TorrentStatus.Disabled : TorrentStatus.Ready)">@(item.Status == TorrentStatus.Disabled ? "Enable" : "Disable")</button>
                        <button asp-action="Download" type="submit" asp-route-id="@item.TorrentId">Download</button>
                    </td>
                </tr>
                <tr class="@(item.Status == TorrentStatus.Disabled ? "disabled-torrent" : "")">
                    <td colspan="4" style="padding: 0 50px; border-top: none;">
                        @Html.DisplayFor(modelItem => item.DownloadProgress)
                    </td>
                </tr>
                <tr data-description="@item.TorrentId" style="display: none;">                    
                    <td colspan="4" style="padding: 8px; border-top: none;">
                        <pre>@Html.Raw(item.Description)</pre>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

@section Scripts
{
<script type="text/javascript">
    var configChart = {
        type: 'line',
        data: {
            labels: [],
            datasets: []
        },
        options: {
            responsive: true,
            title: {
                display: true,
                text: 'Downloads'
            },
            tooltips: {
                mode: 'index',
                intersect: false,
                callbacks: {
                    label: function (tooltipItem, data) {
                        var label = data.datasets[tooltipItem.datasetIndex].label || '';

                        if (label) {
                            label += ': ';
                        }
                        return label + formatBytes(tooltipItem.yLabel) + '/s';
                    }
                }
            },
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: '% Complete'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Download Rate'
                    },
                    ticks: {
                        callback: function (value, index, values) {
                            return formatBytes(value) + '/s';
                        }
                    }
                }]
            }
        }
    };

    var COLORS = [
        '#4dc9f6',
        '#f67019',
        '#f53794',
        '#537bc4',
        '#acc236',
        '#166a8f',
        '#00a950',
        '#58595b',
        '#8549ba'
    ];
    function initializeChart() {
        var ctx = document.getElementById('graph').getContext('2d');
        ctx.height = 320;
        window.downloadChart = new Chart(ctx, configChart);
    }
    function addChart(torrentId, title) {
        var color = COLORS[configChart.data.datasets.length];

        configChart.data.datasets.push({
            id: torrentId,
            label: title,
            backgroundColor: color,
            borderColor: color,
            fill: false,
            data: []
        });
        window.downloadChart.update();
    }
    function updateChart(torrentId, bytesDownloaded, percentComplete, downloadRate) {
        /*
        if (configChart.data.labels.length == 10) {
            configChart.data.labels.shift();
            configChart.data.datasets[0].data.shift();
        }
        */
        configChart.data.labels.push(formatNumber(percentComplete, 1) + '%');
        var ds = configChart.data.datasets.filter(d => d.id == torrentId)[0];
        ds.data.push(downloadRate);

        window.downloadChart.update();
    }
    function updateProgressBar(torrentId, bytesDownloaded, totalBytes, percentComplete, downloadRate) {
        $('div[data-torrent="' + torrentId + '"] div.progress-bar')
            .css('width', percentComplete + '%')
            .attr('aria-valuenow', percentComplete)
            .siblings('small')
            .text(formatNumber(percentComplete, 1) + '%');
        $('div[data-torrent="' + torrentId + '"] div:nth-child(2) span')
            .text(formatBytes(bytesDownloaded) + ' of ' + formatBytes(totalBytes) + ' at ' + formatBytes(downloadRate) + '/s');
    }

    function toggle(id) {
        $('tr[data-description="' + id + '"]').toggle();
        return false;
    }

    function formatNumber(value, decimals) {
        return parseFloat(Math.round(value * (decimals * 10)) / (decimals * 10)).toFixed(decimals).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }
    function formatBytes(bytes) {
        if (bytes > Math.pow(2, 30))
            return formatNumber((bytes / Math.pow(2, 30)), 1) + 'GB';
        else if (bytes > Math.pow(2, 20))
            return formatNumber((bytes / Math.pow(2, 20)), 1) + 'MB';
        else if (bytes > Math.pow(2, 10))
            return formatNumber((bytes / Math.pow(2, 10)), 1) + 'KB';
        else
            return formatNumber(bytes, 1);
    }

    jQuery(document).ready(function () {
        initializeChart();
        addChart('http://thepiratebay.org/torrent/21556627/', 'Black Panther');

        var totalBytes = 1832543190;
        var currentProgress = 0.0;
        var downloadRate = 0.0;

        var timer = setInterval(() => {
            currentProgress += (Math.random() * 8.3);
            downloadRate = 1024 * (12.3 + (Math.random() * 3487.2));
            if (currentProgress > 100) {
                currentProgress = 100;
                clearInterval(timer);
            }
            var downloaded = (totalBytes * (currentProgress / 100.0));

            updateChart('http://thepiratebay.org/torrent/21556627/', downloaded, currentProgress, downloadRate);
            updateProgressBar('http://thepiratebay.org/torrent/21556627/', downloaded, totalBytes, currentProgress, downloadRate);
        }, 500);
    });
</script>
}